### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ChesVerv** [nationalparkservice/SET-viz#41]
Some sites seem to be hanging up. Specifically, TIMU01 and TIMU27. There may be more, I wasn’t sure if you needed to address those individually. When trying to look at change in pin heights for some sites (probably a lack of data) the screen goes grey and I eventually have to back all of the way out in order to resume.

**Comment by ellenmonster** [comment]
Issue was for stations or station-arms that had no data at all for pin change, only N/A (e.g., if only one survey event then there could be no calculation of pin height). Fixed by converting N/A's to an explicit text of "N/A" and assigning a color to the level "N/A". Pull the updated dashboard to see change--if that doesn't fix this issue, then please re-open the issue with further comments. As a side note, "Bug" does not count as a useful issue title :)
