### ISSUE TITLE
New Bug with "Exclude From Analysis"

### ISSUE THREAD

**Issue by ChesVerv** [nationalparkservice/SET-viz#46]
I was working with the Analysis Flags in the database to see what would happen in the visualizer and I have found that when more than one number is flagged for exclusion from analysis that the whole position gets shaded as a large change. As usual attached screen shots.
[Visualizer Flag Shading.docx](https://github.com/nationalparkservice/SET-viz/files/9879472/Visualizer.Flag.Shading.docx)

**Comment by ellenmonster** [comment]
Can you "keep" your TIMU03 test data in the database with 3 analysis flags checked, for now? I will look into this bug at the end of today after meetings are over, to try to get it fixed asap--then you can return the data in the database to what it was before (just one analysis flag)

**Comment by ChesVerv** [comment]
Let me go back and flag them

**Comment by ellenmonster** [comment]
@ChesVerv Seems like the pin data has two records that are exactly identical except that in one record, pin_code = EIA and in the other, pin_code = Hole (see highlighted yellow records in image). When the dashboard reads these data, it throws an error that the number of records does not match what it's expecting. So the issue is not that there are multiple "exclude from analysis" pins, but rather that this pin has a duplicate record in the database (almost duplicate--differs only in pin_code) and that throws the dashboard for a loop. So the question is: When a user selects multiple pin codes, does the database automatically create duplicate records then (or the View query that gives us the pin export does this--I'm guessing that is what is actually happening)? If that is the case, we should figure out another way to represent a record with multiple pin codes, instead of generating multiple records that differ only by pin code. This is something we should discuss with Wendy and Adam, I think.

![Ches](https://user-images.githubusercontent.com/32928055/198410657-133a2df4-74ee-47af-8fb4-a232b839d4c7.PNG)

**Comment by wwrightuga** [comment]
@ellenmonster  @ChesVerv and I don't know why it won't let me tag Adam. This is a bigger new issue that Adam and I will need to take a look at when he and I are both in. The 'Exclude from analysis' should not be showing up as a 'field flag.' The database is set up to only allow one (field flag), so the fact that it lumps the 'analysis flags' into the same field, and creates a new record, is new information. The workaround (that Ches and I already talked about for some other reason) is to not use the analysis flags for now, but that shouldn't be a long-term solution.

**Comment by ellenmonster** [comment]
I think this was fixed when the database was fixed
