### ISSUE TITLE
Tabs - naming issues

### ISSUE THREAD

**Issue by NPSlynch** [nationalparkservice/SET-viz#48]
1) major tab naming - Two main types of data - a) SET data and b) MH data.

- Big Picture Summary - fine with this
- Pin Heights - Should mention SET. Maybe "SET Pin Heights"
- Change in Pin Heights - should also mention SET. "SET Pin Height Change"
- MH data - no problems
- Export for NERDS - no problems

2) Pin Height TAB:
a) Heat Plots tab - This should not say Heat Plots - Maybe say "Raw Pin data" or "Raw SET Pin data"

b) Use of the term DATUM ALERTS - Please don't use DATUM since it's confusing me with the use of survey datums and hydrology datums

**Comment by ellenmonster** [comment]
Made requested changes--mostly. The exception is in renaming the Heat Plots tab to say "Raw Pin Data" or "Raw SET Pin Data"... because: 1) depending on what the user selects, the heat plots may show raw pin data and/OR CHANGE in raw pin data; 2) the Line Plots tab also shows Raw Pin Data (but it's line plots of the raw data instead of heat plots of the raw data). Should re-discuss what tab names would make most sense

**Comment by NPSlynch** [comment]
Actually - I now think the TAB for the SET data should be "SET Pin Data" instead of "SET Pin Heights". 

This would make the tabs for the SET and MH data have similar labels and be more informative....

Jimbo (Sorry!)

**Comment by ellenmonster** [comment]
We can do all the re-naming in-person during a meeting, just keep a list and we can take care of it all at once


Ellen Cheng (She/Her/Hers)



Regional Quantitative Ecologist, Inventory and Monitoring

Southeast Regional Office

100 Alabama St. SW

Atlanta, GA  30303



(c) (929) 600-4244 [remote work]



Confidentiality Notice:

This e-mail is intended for the use of the individual or entity to which it is addressed.  It may contain information that is privileged, confidential, or otherwise protected by applicable law.  If you are not the intended recipient or the employee or agent responsible for delivery of this e-mail to the intended recipient, you are hereby notified that any dissemination, distribution, copying, or use of this e-mail or its contents is strictly prohibited.  If you received this e-mail in error, please notify the sender immediately and destroy all copies.

________________________________
From: Jim Lynch ***@***.***>
Sent: Wednesday, March 20, 2024 11:31 AM
To: nationalparkservice/SET-viz ***@***.***>
Cc: Cheng, Ellen ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [nationalparkservice/SET-viz] Tabs - naming issues (Issue #48)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Actually - I now think the TAB for the SET data should be "SET Pin Data" instead of "SET Pin Heights".

This would make the tabs for the SET and MH data have similar labels and be more informative....

Jimbo (Sorry!)

**Comment by ellenmonster** [comment]
I think we took care of this in our last meeting w/JP?

**Comment by NPSlynch** [comment]
I believe you are correct.
