### ISSUE TITLE
Legend Comments for LINE Plots

### ISSUE THREAD

**Issue by NPSlynch** [nationalparkservice/SET-viz#49]
Location: Pin Heights Tab / Line Plots tab

1) SET Arm - Maybe call this "SET Arm Direction" or "SET Direction". But you can also leave it... I don't use the term ARM so I may be different from the others.

2) Have the legend data align with its particular graphic. Not one long list.
   For example:  SET M5-1 - directions A,B,C,D.  These would appear to the right of the graphic
                          SET M5-2 - these legends would appear next to the graphic.
                           etc..

3) Legend order -I Personally prefer the order of the SET ARM legend goes, ABCD.. Not sure how they are currently sorted but it bugs me!
                Example - M5-1A, M5-1B, M5-1C, M5-1D

4) I mentioned this in another comment but I think it would be good to have the linear trend value in this legend and NOT necessarily in the hover box.... I think the legend is the priority. I'd like to see all the trend values without having to move the mouse around and I think the legend would be a good place.

**Comment by NPSlynch** [comment]
I noticed that the line plots are a fixed size and do not take advantage of empty space to the right. I think it would be better if they could be a bit wider.

**Comment by ellenmonster** [comment]
Okay, I have spent all day on this (not to mention having also unsuccessfully tried to fix this problem in past years it is such a DUMB thing that interactive plots cannot have multiple plots on a page, each with its own legend! This issue has been discussed over and over on the plotly (interactive R plots) forum and has been posted on their GitHub since 2020, without resolution. So here are the options now:
- multiple plots on a page and each has its corresponding legend, but the plots are NOT INTERACTIVE (i.e., you cannot hover over them to find out which pin# an unusual line belongs to--you will be able to tell the SET direction from the legend, but not pin#)
- multiple INTERACTIVE plots on a page but no legend (i.e., you have to hover over a line to find out what SET direction (arm) and/or pin# it is because there will be no separate legend telling you what color is what SET direction
- checkbox for you to select what station to display and it will be interactive with a legend, but you can't see multiple stations at a time (similar to how heatplots are set up--you select what station you want to see

None of these are ideal, but these are the current options. Let me know which you would prefer

**Comment by ellenmonster** [comment]
Went with the "way to go"
