### ISSUE TITLE
Plots not showing up on map

### ISSUE THREAD

**Issue by ChesVerv** [nationalparkservice/SET-viz#81]
Maps at CAHA11 not showing all of the plots (only one shown). Map for CALO SET showing no plots

**Comment by ellenmonster** [comment]
On the first survey date for each station there is no calculated 'change in pin heights' since there was no prior survey to calculate change from. For CAHA, the stations had different start dates (let me know if that should not be the case) so that's why you only see one station for that default map year but when you look at other map years you will see the other stations show up. I modified the dashboard maps so the first(default) map date is the earliest date for which data is available for at least one station (so that means that the first survey event is always skipped in the maps since there will be no calculated 'change in pin heights')
